name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Use NodeJS 13.x
      uses: actions/setup-node@v1
      with:
        node-version: 13.x
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build